title: θεόφιλος Journey
description: "NLP Books semantic mapping project"
author:
  name: "Jorge Murillo"
  email: "murillo.cjr@gmail.com"
  url: "https://murillocjr.github.io/theophilusnlp"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "SomeHacker"
year : "2020"

# deployment
host: 0.0.0.0
port: 4000

